[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py --mode web"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.envs]
RAILWAY_ENVIRONMENT = "production"

# Tối ưu resource limits
[deploy.resources]
# Giới hạn CPU và RAM để kiểm soát chi phí
cpu = 0.25  # 25% CPU thay vì 50%
memory = 256  # 256MB thay vì 512MB

[environments.production.variables]
# Environment-specific variables
DEBUG = "False"
PYTHONUNBUFFERED = "1"
