services:
  - type: web
    name: tele-kanban-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py --mode both
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: RENDER
        value: "true"
      - key: LOG_LEVEL
        value: "INFO"
      - key: POLLING_TIMEOUT
        value: "30"
      - key: CONNECTION_TIMEOUT
        value: "30"
      - key: BOT_TOKEN
        value: "your_bot_token_here"
    autoDeploy: false
